/**
 * Deterministic domain bindings for the accepted 18-anchor expression kernel.
 * Bindings for the native production subset align with GasperExpressionFixtures;
 * remaining historical anchors are recovered from affect + family geometry grammar.
 */

import type { DomainScalarMap } from "../GasperDomainState";

export type ExpressionBindingSpec = {
  id: string;
  family: string;
  label: string;
  note: string;
  bindings: DomainScalarMap;
};

/** Mature Neutral floor — Dormant Maintain quality baseline for face/shell/energy. */
const NEUTRAL_SETTLED: DomainScalarMap = {
  energy_level: 0.52,
  energy_pulse: 0.16,
  energy_lag: 0.35,
  eye_openness: 0.56,
  eye_spacing: 0,
  mouth_openness: 0.32,
  mouth_width: 1,
  face_scale: 1,
  gaze: 0.02,
  corner_pull_l: 0.02,
  corner_pull_r: 0.02,
  brow_raise: 0.04,
  upper_lid_aperture: 0.56,
  lower_lid_aperture: 0.48,
  eye_tilt: 0,
  inter_eye_relation: 0,
  mouth_curvature: 0.04,
  mouth_aperture: 0.32,
  cheek_tension: 0.3,
  face_plane_tension: 0.34,
  contour_bias: 0,
  face_asymmetry: 0.01,
  gaze_action: 0.02,
  relief_amplitude: 0.42,
  skin_tension: 0.36,
  internal_glow: 0.48,
  face_emissive: 0.32,
  overall_height: 1,
  overall_width: 1,
  crown_height: 0.04,
  ground_flattening: 0,
  inertia: 0.35,
  settling: 0.42,
  rebound: 0.14,
};

/** Full 18-anchor binding table (production path). */
export const EXPRESSION_ANCHOR_BINDINGS: Record<string, ExpressionBindingSpec> = {
  "neutral-settled": {
    id: "neutral-settled",
    family: "neutral",
    label: "Settled",
    note: "Mature Neutral floor: friendly, intelligent, slightly up-to-something. Continuous one-body rest — not a discrete pose swap.",
    bindings: { ...NEUTRAL_SETTLED },
  },
  "neutral-social": {
    id: "neutral-social",
    family: "neutral",
    label: "Social",
    note: "Slightly more open and receptive neutral.",
    bindings: {
      energy_level: 0.58,
      energy_pulse: 0.2,
      eye_openness: 0.62,
      mouth_openness: 0.36,
      mouth_width: 1.04,
      face_scale: 1.02,
      face_emissive: 0.4,
      relief_amplitude: 0.45,
      overall_height: 1.01,
      overall_width: 1.01,
    },
  },
  "neutral-wry": {
    id: "neutral-wry",
    family: "neutral",
    label: "Wry",
    note: "Slight knowing tilt with controlled asymmetry.",
    bindings: {
      energy_level: 0.55,
      energy_pulse: 0.22,
      eye_openness: 0.58,
      eye_spacing: 0.02,
      mouth_openness: 0.3,
      mouth_width: 1.02,
      corner_pull_l: 0.06,
      corner_pull_r: -0.02,
      gaze: 0.08,
      face_scale: 1.01,
      face_emissive: 0.36,
      relief_amplitude: 0.44,
    },
  },
  "listening-open": {
    id: "listening-open",
    family: "listening",
    label: "Open",
    note: "Receptive attention — whole-face: raised brow, open upper lid, soft mouth, attend-gaze.",
    bindings: {
      energy_level: 0.64,
      energy_pulse: 0.22,
      energy_lag: 0.28,
      eye_openness: 0.607,
      eye_spacing: 0.06,
      mouth_openness: 0.24,
      mouth_width: 1.02,
      face_scale: 1.02,
      gaze: 0.136,
      corner_pull_l: 0.021,
      corner_pull_r: 0.0,
      brow_raise: 0.22,
      upper_lid_aperture: 0.68,
      lower_lid_aperture: 0.42,
      eye_tilt: 0.04,
      inter_eye_relation: 0.06,
      mouth_curvature: 0.02,
      mouth_aperture: 0.24,
      cheek_tension: 0.28,
      face_plane_tension: 0.38,
      contour_bias: 0.04,
      face_asymmetry: 0.03,
      gaze_action: 0.16,
      relief_amplitude: 0.5,
      skin_tension: 0.347,
      internal_glow: 0.56,
      face_emissive: 0.4,
      overall_height: 1.02,
      overall_width: 1.015,
      crown_height: 0.08,
      inertia: 0.32,
      settling: 0.4,
      rebound: 0.18,
    },
  },
  "listening-focus": {
    id: "listening-focus",
    family: "listening",
    label: "Focus",
    note: "Narrowed aperture of attention.",
    bindings: {
      energy_level: 0.62,
      energy_pulse: 0.28,
      energy_lag: 0.4,
      eye_openness: 0.6,
      eye_spacing: -0.04,
      mouth_openness: 0.22,
      face_scale: 0.99,
      gaze: 0.1,
      relief_amplitude: 0.52,
      skin_tension: 0.48,
      internal_glow: 0.52,
      crown_height: 0.1,
      inertia: 0.4,
    },
  },
  "listening-warm": {
    id: "listening-warm",
    family: "listening",
    label: "Warm",
    note: "Affiliative receptive listen.",
    bindings: {
      energy_level: 0.66,
      energy_pulse: 0.24,
      eye_openness: 0.66,
      mouth_openness: 0.34,
      mouth_width: 1.06,
      corner_pull_l: 0.05,
      corner_pull_r: 0.05,
      face_scale: 1.03,
      gaze: 0.08,
      face_emissive: 0.48,
      internal_glow: 0.58,
      relief_amplitude: 0.48,
    },
  },
  "thinking-knit": {
    id: "thinking-knit",
    family: "thinking",
    label: "Knit",
    note: "Executing/Thinking: inward knit — drawn brow, dual-lid compress, compressed mouth. Continuous tissue deformation, not eye/mouth sprite swap.",
    bindings: {
      energy_level: 0.58,
      energy_pulse: 0.36,
      energy_lag: 0.55,
      eye_openness: 0.462,
      eye_spacing: -0.08,
      mouth_openness: 0.18,
      mouth_width: 0.96,
      face_scale: 0.98,
      gaze: -0.085,
      corner_pull_l: -0.054,
      corner_pull_r: -0.012,
      brow_raise: -0.14,
      upper_lid_aperture: 0.4,
      lower_lid_aperture: 0.62,
      eye_tilt: -0.08,
      inter_eye_relation: -0.08,
      mouth_curvature: -0.06,
      mouth_aperture: 0.18,
      cheek_tension: 0.48,
      face_plane_tension: 0.58,
      contour_bias: -0.04,
      face_asymmetry: -0.06,
      gaze_action: -0.1,
      relief_amplitude: 0.58,
      skin_tension: 0.545,
      internal_glow: 0.5,
      face_emissive: 0.34,
      overall_height: 0.99,
      overall_width: 0.975,
      crown_height: 0.12,
      ground_flattening: 0.02,
      inertia: 0.48,
      settling: 0.38,
      rebound: 0.12,
    },
  },
  "thinking-scan": {
    id: "thinking-scan",
    family: "thinking",
    label: "Scan",
    note: "Exploratory cognitive scan with gaze microvariation.",
    bindings: {
      energy_level: 0.6,
      energy_pulse: 0.38,
      energy_lag: 0.48,
      eye_openness: 0.54,
      eye_spacing: 0.02,
      mouth_openness: 0.24,
      face_scale: 0.99,
      gaze: 0.12,
      relief_amplitude: 0.55,
      skin_tension: 0.46,
      internal_glow: 0.52,
      crown_height: 0.1,
      inertia: 0.38,
    },
  },
  "thinking-resolve": {
    id: "thinking-resolve",
    family: "thinking",
    label: "Resolve",
    note: "Converging solution bridge toward recognition.",
    bindings: {
      energy_level: 0.64,
      energy_pulse: 0.32,
      energy_lag: 0.38,
      eye_openness: 0.6,
      mouth_openness: 0.3,
      mouth_width: 1.04,
      face_scale: 1.02,
      gaze: 0.04,
      face_emissive: 0.45,
      internal_glow: 0.56,
      relief_amplitude: 0.5,
      crown_height: 0.09,
      rebound: 0.22,
    },
  },
  "mischievous-spark": {
    id: "mischievous-spark",
    family: "mischievous",
    label: "Spark",
    note: "Recognition: bright spark — open dual lids, lifted brow, approach gaze, mouth curve up. Continuous one-body lift.",
    bindings: {
      energy_level: 0.76,
      energy_pulse: 0.46,
      energy_lag: 0.2,
      eye_openness: 0.648,
      eye_spacing: 0.05,
      mouth_openness: 0.4,
      mouth_width: 1.08,
      corner_pull_l: 0.117,
      corner_pull_r: 0.082,
      face_scale: 1.035,
      gaze: 0.153,
      brow_raise: 0.28,
      upper_lid_aperture: 0.76,
      lower_lid_aperture: 0.36,
      eye_tilt: 0.06,
      inter_eye_relation: 0.05,
      mouth_curvature: 0.18,
      mouth_aperture: 0.4,
      cheek_tension: 0.44,
      face_plane_tension: 0.36,
      contour_bias: 0.08,
      face_asymmetry: 0.05,
      gaze_action: 0.18,
      face_emissive: 0.56,
      internal_glow: 0.66,
      relief_amplitude: 0.54,
      skin_tension: 0.388,
      overall_height: 1.035,
      overall_width: 1.02,
      crown_height: 0.12,
      ground_flattening: 0,
      inertia: 0.28,
      settling: 0.32,
      rebound: 0.32,
    },
  },
  "mischievous-side": {
    id: "mischievous-side",
    family: "mischievous",
    label: "Side",
    note: "Lateral tease with intentional asymmetry.",
    bindings: {
      energy_level: 0.7,
      energy_pulse: 0.4,
      eye_openness: 0.66,
      eye_spacing: 0.06,
      mouth_openness: 0.38,
      mouth_width: 1.06,
      corner_pull_l: 0.14,
      corner_pull_r: -0.04,
      face_scale: 1.02,
      gaze: 0.2,
      face_emissive: 0.5,
      internal_glow: 0.6,
      relief_amplitude: 0.5,
    },
  },
  "mischievous-hold": {
    id: "mischievous-hold",
    family: "mischievous",
    label: "Hold",
    note: "Contained mischief; ablation control fixture.",
    bindings: {
      energy_level: 0.66,
      energy_pulse: 0.32,
      eye_openness: 0.62,
      mouth_openness: 0.36,
      mouth_width: 1.05,
      corner_pull_l: 0.08,
      corner_pull_r: 0.06,
      face_scale: 1.02,
      gaze: 0.1,
      face_emissive: 0.46,
      internal_glow: 0.55,
      relief_amplitude: 0.48,
      settling: 0.4,
    },
  },
  "pleased-glow": {
    id: "pleased-glow",
    family: "pleased",
    label: "Glow",
    note: "Pleased: warm satisfaction — soft brow lift, dual-lid soft open, strong mouth lift, cheek raise. Continuous tissue, one body.",
    bindings: {
      energy_level: 0.66,
      energy_pulse: 0.28,
      energy_lag: 0.3,
      eye_openness: 0.541,
      eye_spacing: 0.02,
      mouth_openness: 0.38,
      mouth_width: 1.09,
      corner_pull_l: 0.161,
      corner_pull_r: 0.147,
      face_scale: 1.025,
      gaze: 0.034,
      brow_raise: 0.1,
      upper_lid_aperture: 0.58,
      lower_lid_aperture: 0.44,
      eye_tilt: 0.02,
      inter_eye_relation: 0.02,
      mouth_curvature: 0.28,
      mouth_aperture: 0.38,
      cheek_tension: 0.52,
      face_plane_tension: 0.3,
      contour_bias: 0.05,
      face_asymmetry: 0.02,
      gaze_action: 0.04,
      face_emissive: 0.54,
      internal_glow: 0.64,
      relief_amplitude: 0.5,
      skin_tension: 0.377,
      overall_height: 1.02,
      overall_width: 1.02,
      crown_height: 0.07,
      ground_flattening: 0,
      inertia: 0.3,
      settling: 0.48,
      rebound: 0.22,
    },
  },
  "pleased-soft": {
    id: "pleased-soft",
    family: "pleased",
    label: "Soft please",
    note: "Warm soft approval without exaggeration.",
    bindings: {
      energy_level: 0.6,
      energy_pulse: 0.24,
      eye_openness: 0.58,
      mouth_openness: 0.4,
      mouth_width: 1.08,
      face_scale: 1.02,
      corner_pull_l: 0.08,
      corner_pull_r: 0.08,
      face_emissive: 0.48,
      internal_glow: 0.55,
      relief_amplitude: 0.48,
    },
  },
  "pleased-bright": {
    id: "pleased-bright",
    family: "pleased",
    label: "Bright",
    note: "Upper-bound celebratory lift (showcase prefers contained).",
    bindings: {
      energy_level: 0.74,
      energy_pulse: 0.38,
      eye_openness: 0.7,
      mouth_openness: 0.48,
      mouth_width: 1.14,
      corner_pull_l: 0.14,
      corner_pull_r: 0.14,
      face_scale: 1.05,
      face_emissive: 0.62,
      internal_glow: 0.72,
      relief_amplitude: 0.54,
      overall_height: 1.05,
      crown_height: 0.12,
      rebound: 0.3,
    },
  },
  "blocked-stall": {
    id: "blocked-stall",
    family: "blocked",
    label: "Stall",
    note: "Lower-arousal goal incongruence.",
    bindings: {
      energy_level: 0.34,
      energy_pulse: 0.1,
      energy_lag: 0.65,
      eye_openness: 0.4,
      eye_spacing: -0.08,
      mouth_openness: 0.16,
      mouth_width: 0.9,
      face_scale: 0.97,
      gaze: 0.02,
      corner_pull_l: -0.08,
      corner_pull_r: -0.08,
      relief_amplitude: 0.32,
      skin_tension: 0.62,
      internal_glow: 0.28,
      face_emissive: 0.16,
      overall_height: 0.96,
      overall_width: 0.97,
      ground_flattening: 0.08,
      inertia: 0.55,
      settling: 0.3,
    },
  },
  "blocked-guard": {
    id: "blocked-guard",
    family: "blocked",
    label: "Guard",
    note: "Defensive withdraw without fear caricature.",
    bindings: {
      energy_level: 0.36,
      energy_pulse: 0.14,
      energy_lag: 0.6,
      eye_openness: 0.38,
      eye_spacing: -0.1,
      mouth_openness: 0.14,
      mouth_width: 0.86,
      face_scale: 0.95,
      gaze: -0.06,
      corner_pull_l: -0.1,
      corner_pull_r: -0.1,
      relief_amplitude: 0.3,
      skin_tension: 0.7,
      internal_glow: 0.26,
      face_emissive: 0.14,
      overall_height: 0.94,
      overall_width: 0.94,
      ground_flattening: 0.1,
      inertia: 0.58,
    },
  },
  "blocked-strain": {
    id: "blocked-strain",
    family: "blocked",
    label: "Strain",
    note: "Blocked: guarded strain — compressed brow, dual-lid guard, tight down-curve mouth, high plane tension. Continuous compression.",
    bindings: {
      energy_level: 0.36,
      energy_pulse: 0.12,
      energy_lag: 0.7,
      eye_openness: 0.441,
      eye_spacing: -0.12,
      mouth_openness: 0.14,
      mouth_width: 0.88,
      face_scale: 0.96,
      gaze: 0.042,
      corner_pull_l: -0.135,
      corner_pull_r: -0.107,
      brow_raise: -0.22,
      upper_lid_aperture: 0.34,
      lower_lid_aperture: 0.7,
      eye_tilt: -0.04,
      inter_eye_relation: -0.12,
      mouth_curvature: -0.22,
      mouth_aperture: 0.14,
      cheek_tension: 0.72,
      face_plane_tension: 0.78,
      contour_bias: -0.12,
      face_asymmetry: -0.04,
      gaze_action: 0.05,
      relief_amplitude: 0.34,
      skin_tension: 0.759,
      internal_glow: 0.3,
      face_emissive: 0.16,
      overall_height: 0.94,
      overall_width: 0.95,
      crown_height: 0.06,
      ground_flattening: 0.12,
      inertia: 0.6,
      settling: 0.24,
      rebound: 0.06,
    },
  },
};

/**
 * FormMaster / native / hero-pack ids → kernel ids.
 * Must stay aligned with formMasterBridge FORM_MASTER_TO_KERNEL
 * (plus a few non-catalog bridges).
 */
export const BINDING_ALIASES: Record<string, string> = {
  "listening-orient": "listening-open",
  "listening-hold": "listening-focus",
  "listening-receive": "listening-warm",
  "mischievous-left": "mischievous-side",
  "mischievous-right": "mischievous-hold",
  "pleased-warm": "pleased-glow",
  "pleased-contained": "pleased-soft",
  "blocked-uncertain": "blocked-stall",
  "blocked-compressed": "blocked-guard",
  "blocked-retry": "blocked-strain",
  recovering: "neutral-settled",
  "recognition-spark": "mischievous-spark",
};

export function resolveBindingId(id: string): string | null {
  if (EXPRESSION_ANCHOR_BINDINGS[id]) return id;
  const a = BINDING_ALIASES[id];
  if (a && EXPRESSION_ANCHOR_BINDINGS[a]) return a;
  return null;
}

export function getAnchorBindings(id: string): ExpressionBindingSpec | null {
  const resolved = resolveBindingId(id);
  return resolved ? EXPRESSION_ANCHOR_BINDINGS[resolved] : null;
}

export function listAnchorBindingIds(): string[] {
  return Object.keys(EXPRESSION_ANCHOR_BINDINGS).sort();
}
