/**
 * Complete eight-state (+wake) character profiles.
 * Re-authored as ONE coherent Gasper character — not a second competing catalog.
 * Channel values coherent with EIGHT_STATE_VISUAL_ENDPOINTS + facial semantic targets.
 * Signatures via channel/energy/shell/face co-modulation — no theatrical icons.
 */

import type {
  CharacterChannelMap,
  CharacterStateProfile,
  EightStateVisualId,
} from "./types";

/** Required multi-domain channel keys every profile must cover. */
export const REQUIRED_PROFILE_CHANNEL_KEYS = [
  "overall_width",
  "overall_height",
  "crown_height",
  "lower_body_fullness",
  "ground_flattening",
  "face_scale",
  "eye_openness",
  "eye_spacing",
  "gaze",
  "mouth_openness",
  "mouth_width",
  "corner_pull_l",
  "corner_pull_r",
  "energy_level",
  "energy_pulse",
  "energy_lag",
  "internal_glow",
  "face_emissive",
  "pearl_intensity",
  "skin_tension",
  "relief_amplitude",
  "inertia",
  "settling",
  "rebound",
  "motion",
  "rim",
  "key_intensity",
  "center_of_mass_y",
] as const;

const SIG_CHANNELS = [
  "eye_openness",
  "eye_spacing",
  "mouth_openness",
  "mouth_width",
  "face_scale",
  "gaze",
  "corner_pull_l",
  "corner_pull_r",
  "energy_level",
  "energy_pulse",
  "internal_glow",
  "face_emissive",
  "overall_height",
  "overall_width",
  "skin_tension",
  "ground_flattening",
  "inertia",
  "motion",
  "pearl_intensity",
] as const;

function profile(
  partial: Omit<CharacterStateProfile, "qualityFloorRef"> & {
    qualityFloorRef?: "dormant-orbit-maintain";
  },
): CharacterStateProfile {
  return {
    qualityFloorRef: "dormant-orbit-maintain",
    ...partial,
  };
}

/**
 * Canonical eight-state + wake character profiles.
 * Dormant Maintain is the quality floor — most conservative residual orbit.
 * Neutral encodes friendly/intelligent/slightly-up-to-something.
 */
export const GASPER_STATE_PROFILES: Record<
  EightStateVisualId,
  CharacterStateProfile
> = Object.freeze({
  // ─── 1. Neutral ───────────────────────────────────────────────────────────
  "presence-neutral-settled": profile({
    stateId: "presence-neutral-settled",
    label: "Neutral · Settled",
    semanticIntent:
      "Friendly, intelligent, slightly up-to-something resting presence.",
    personalityRead: {
      friendly: 0.72,
      intelligent: 0.78,
      slightlyUpToSomething: 0.55,
      valence: 0.12,
      arousal: 0.28,
      summary:
        "Friendly, intelligent, slightly up-to-something resting presence.",
    },
    visualSignature: {
      domains: ["face", "shell", "energy", "motion"],
      primaryCue: "relaxed-almond-availability",
      secondaryCue: "balanced-pearl-glow",
      signatureChannels: SIG_CHANNELS,
    },
    channels: {
      overall_width: 1.0,
      overall_height: 1.015,
      crown_height: 0.04,
      lower_body_fullness: 1.0,
      ground_flattening: 0.0,
      face_scale: 1.0,
      eye_openness: 0.56,
      eye_spacing: 0.02,
      gaze: 0.04,
      mouth_openness: 0.32,
      mouth_width: 1.0,
      corner_pull_l: 0.03,
      corner_pull_r: -0.02,
      energy_level: 0.52,
      energy_pulse: 0.16,
      energy_lag: 0.35,
      energy_occlusion: 0.12,
      relief_amplitude: 0.42,
      relief_motion_coupling: 0.28,
      relief_energy_coupling: 0.36,
      skin_tension: 0.36,
      skin_damping: 0.52,
      skin_coupling: 0.42,
      pearl_intensity: 0.55,
      internal_glow: 0.48,
      face_emissive: 0.32,
      absorption: 0.18,
      roughness: 0.34,
      clearcoat: 0.4,
      key_intensity: 0.58,
      key_direction: 0.05,
      rim: 0.42,
      inertia: 0.32,
      secondary_lag: 0.38,
      rebound: 0.22,
      settling: 0.55,
      motion: 0.18,
      center_of_mass_y: 0.02,
    },
    layerActivations: { shell: 1, energy: 0.55, face: 0.85, motion: 0.35 },
    silhouetteDelta: { width: 0, height: 0.015, crown: 0.04, ground: 0 },
    volumePolicy: { conserve: true, areaTarget: 1.015, squashStretch: 0 },
    centerOfMass: { x: 0, y: 0.02 },
    facialAttachment: {
      attached: true,
      latticeId: "feature-anchors-v1",
      faceScale: 1.0,
      eyeOpenness: 0.56,
      mouthOpenness: 0.32,
      residualBudget: 0.05,
    },
    materialMods: {
      pearlIntensity: 0.55,
      roughness: 0.34,
      clearcoat: 0.4,
      absorption: 0.18,
    },
    paletteMods: {
      rim: 0.42,
      keyIntensity: 0.58,
      internalGlow: 0.48,
      faceEmissive: 0.32,
    },
    embodimentId: "presence",
    expressionAffinity: "neutral-settled",
  }),

  // ─── 2. Listening ─────────────────────────────────────────────────────────
  "presence-listening-receive": profile({
    stateId: "presence-listening-receive",
    label: "Listening · Receive",
    semanticIntent:
      "Attention organized toward target; eyes available; energy directional.",
    personalityRead: {
      friendly: 0.7,
      intelligent: 0.82,
      slightlyUpToSomething: 0.4,
      valence: 0.18,
      arousal: 0.42,
      summary: "Attentive receive — open eyes, directional energy, quiet mouth.",
    },
    visualSignature: {
      domains: ["face", "shell", "energy", "motion"],
      primaryCue: "forward-gaze-receive",
      secondaryCue: "directional-energy-bias",
      signatureChannels: SIG_CHANNELS,
    },
    channels: {
      overall_width: 1.02,
      overall_height: 1.03,
      crown_height: 0.08,
      lower_body_fullness: 0.98,
      ground_flattening: 0.02,
      face_scale: 1.04,
      eye_openness: 0.66,
      eye_spacing: 0.05,
      gaze: 0.18,
      mouth_openness: 0.24,
      mouth_width: 0.98,
      corner_pull_l: 0.02,
      corner_pull_r: 0.01,
      energy_level: 0.64,
      energy_pulse: 0.22,
      energy_lag: 0.26,
      energy_occlusion: 0.1,
      relief_amplitude: 0.5,
      relief_motion_coupling: 0.34,
      relief_energy_coupling: 0.48,
      skin_tension: 0.42,
      skin_damping: 0.48,
      skin_coupling: 0.5,
      pearl_intensity: 0.56,
      internal_glow: 0.58,
      face_emissive: 0.44,
      absorption: 0.16,
      roughness: 0.32,
      clearcoat: 0.44,
      key_intensity: 0.64,
      key_direction: 0.18,
      rim: 0.46,
      inertia: 0.28,
      secondary_lag: 0.3,
      rebound: 0.26,
      settling: 0.42,
      motion: 0.28,
      center_of_mass_y: 0.03,
    },
    layerActivations: { shell: 1, energy: 0.68, face: 0.92, motion: 0.45 },
    silhouetteDelta: { width: 0.02, height: 0.03, crown: 0.08, ground: 0.02 },
    volumePolicy: { conserve: true, areaTarget: 1.0506, squashStretch: 0.02 },
    centerOfMass: { x: 0, y: 0.03 },
    facialAttachment: {
      attached: true,
      latticeId: "feature-anchors-v1",
      faceScale: 1.04,
      eyeOpenness: 0.66,
      mouthOpenness: 0.24,
      residualBudget: 0.05,
    },
    materialMods: {
      pearlIntensity: 0.56,
      roughness: 0.32,
      clearcoat: 0.44,
      absorption: 0.16,
    },
    paletteMods: {
      rim: 0.46,
      keyIntensity: 0.64,
      internalGlow: 0.58,
      faceEmissive: 0.44,
    },
    embodimentId: "presence",
    expressionAffinity: "listening-orient",
  }),

  // ─── 3. Thinking / Executing ──────────────────────────────────────────────
  "presence-thinking-knit": profile({
    stateId: "presence-thinking-knit",
    label: "Thinking · Knit",
    semanticIntent:
      "Inward knit of attention — focused cognitive work, contained energy pulse.",
    personalityRead: {
      friendly: 0.45,
      intelligent: 0.92,
      slightlyUpToSomething: 0.35,
      valence: 0.05,
      arousal: 0.55,
      summary: "Inward knit — compressed eyes, upper-shell tension, lagged pulse.",
    },
    visualSignature: {
      domains: ["face", "shell", "energy", "motion"],
      primaryCue: "inward-eye-knit",
      secondaryCue: "upper-shell-tension-lag",
      signatureChannels: SIG_CHANNELS,
    },
    channels: {
      overall_width: 0.98,
      overall_height: 0.99,
      crown_height: 0.12,
      lower_body_fullness: 0.97,
      ground_flattening: 0.04,
      face_scale: 0.98,
      eye_openness: 0.48,
      eye_spacing: -0.06,
      gaze: -0.08,
      mouth_openness: 0.2,
      mouth_width: 0.94,
      corner_pull_l: -0.04,
      corner_pull_r: 0.02,
      energy_level: 0.58,
      energy_pulse: 0.35,
      energy_lag: 0.55,
      energy_occlusion: 0.22,
      relief_amplitude: 0.58,
      relief_motion_coupling: 0.4,
      relief_energy_coupling: 0.52,
      skin_tension: 0.54,
      skin_damping: 0.56,
      skin_coupling: 0.55,
      pearl_intensity: 0.52,
      internal_glow: 0.5,
      face_emissive: 0.28,
      absorption: 0.24,
      roughness: 0.38,
      clearcoat: 0.36,
      key_intensity: 0.52,
      key_direction: -0.06,
      rim: 0.4,
      inertia: 0.48,
      secondary_lag: 0.52,
      rebound: 0.18,
      settling: 0.48,
      motion: 0.22,
      center_of_mass_y: 0.04,
    },
    layerActivations: { shell: 1, energy: 0.62, face: 0.8, motion: 0.4 },
    silhouetteDelta: { width: -0.02, height: -0.01, crown: 0.12, ground: 0.04 },
    volumePolicy: { conserve: true, areaTarget: 0.9702, squashStretch: 0.03 },
    centerOfMass: { x: 0, y: 0.04 },
    facialAttachment: {
      attached: true,
      latticeId: "feature-anchors-v1",
      faceScale: 0.98,
      eyeOpenness: 0.48,
      mouthOpenness: 0.2,
      residualBudget: 0.05,
    },
    materialMods: {
      pearlIntensity: 0.52,
      roughness: 0.38,
      clearcoat: 0.36,
      absorption: 0.24,
    },
    paletteMods: {
      rim: 0.4,
      keyIntensity: 0.52,
      internalGlow: 0.5,
      faceEmissive: 0.28,
    },
    embodimentId: "presence",
    expressionAffinity: "thinking-knit",
  }),

  // ─── 4. Recognition ───────────────────────────────────────────────────────
  "presence-recognition-spark": profile({
    stateId: "presence-recognition-spark",
    label: "Recognition · Spark",
    semanticIntent:
      "Bright spark of understanding — approach energy without cartoon surprise.",
    personalityRead: {
      friendly: 0.75,
      intelligent: 0.88,
      slightlyUpToSomething: 0.7,
      valence: 0.55,
      arousal: 0.72,
      summary: "Recognition spark — open aperture, concentrated internal glow.",
    },
    visualSignature: {
      domains: ["face", "shell", "energy", "motion"],
      primaryCue: "aperture-lift-spark",
      secondaryCue: "concentrated-internal-glow",
      signatureChannels: SIG_CHANNELS,
    },
    channels: {
      overall_width: 1.03,
      overall_height: 1.06,
      crown_height: 0.14,
      lower_body_fullness: 1.02,
      ground_flattening: 0.0,
      face_scale: 1.06,
      eye_openness: 0.72,
      eye_spacing: 0.04,
      gaze: 0.1,
      mouth_openness: 0.38,
      mouth_width: 1.06,
      corner_pull_l: 0.1,
      corner_pull_r: 0.06,
      energy_level: 0.78,
      energy_pulse: 0.48,
      energy_lag: 0.18,
      energy_occlusion: 0.08,
      relief_amplitude: 0.62,
      relief_motion_coupling: 0.52,
      relief_energy_coupling: 0.62,
      skin_tension: 0.46,
      skin_damping: 0.4,
      skin_coupling: 0.55,
      pearl_intensity: 0.62,
      internal_glow: 0.72,
      face_emissive: 0.58,
      absorption: 0.12,
      roughness: 0.28,
      clearcoat: 0.52,
      key_intensity: 0.72,
      key_direction: 0.08,
      rim: 0.55,
      inertia: 0.22,
      secondary_lag: 0.24,
      rebound: 0.42,
      settling: 0.32,
      motion: 0.45,
      center_of_mass_y: 0.03,
    },
    layerActivations: { shell: 1, energy: 0.88, face: 0.95, motion: 0.65 },
    silhouetteDelta: { width: 0.03, height: 0.06, crown: 0.14, ground: 0 },
    volumePolicy: { conserve: true, areaTarget: 1.0918, squashStretch: 0.04 },
    centerOfMass: { x: 0, y: 0.03 },
    facialAttachment: {
      attached: true,
      latticeId: "feature-anchors-v1",
      faceScale: 1.06,
      eyeOpenness: 0.72,
      mouthOpenness: 0.38,
      residualBudget: 0.05,
    },
    materialMods: {
      pearlIntensity: 0.62,
      roughness: 0.28,
      clearcoat: 0.52,
      absorption: 0.12,
    },
    paletteMods: {
      rim: 0.55,
      keyIntensity: 0.72,
      internalGlow: 0.72,
      faceEmissive: 0.58,
    },
    embodimentId: "presence",
    expressionAffinity: "pleased-soft",
  }),

  // ─── 5. Comet (Executing Drive) ───────────────────────────────────────────
  "comet-executing-drive": profile({
    stateId: "comet-executing-drive",
    label: "Comet · Executing Drive",
    semanticIntent:
      "Directional reorganization; forward gaze/energy; face remains Gasper.",
    personalityRead: {
      friendly: 0.5,
      intelligent: 0.85,
      slightlyUpToSomething: 0.6,
      valence: 0.2,
      arousal: 0.78,
      summary: "Drive — elongated shell bias, forward gaze, high motion energy.",
    },
    visualSignature: {
      domains: ["face", "shell", "energy", "motion"],
      primaryCue: "forward-drive-elongation",
      secondaryCue: "spectral-energy-envelope",
      signatureChannels: SIG_CHANNELS,
    },
    channels: {
      overall_width: 1.05,
      overall_height: 0.98,
      crown_height: 0.06,
      lower_body_fullness: 0.94,
      ground_flattening: 0.06,
      face_scale: 0.94,
      eye_openness: 0.64,
      eye_spacing: 0.02,
      gaze: 0.22,
      mouth_openness: 0.28,
      mouth_width: 0.96,
      corner_pull_l: 0.0,
      corner_pull_r: 0.02,
      energy_level: 0.74,
      energy_pulse: 0.38,
      energy_lag: 0.22,
      energy_occlusion: 0.14,
      relief_amplitude: 0.56,
      relief_motion_coupling: 0.58,
      relief_energy_coupling: 0.6,
      skin_tension: 0.5,
      skin_damping: 0.42,
      skin_coupling: 0.58,
      pearl_intensity: 0.54,
      internal_glow: 0.66,
      face_emissive: 0.4,
      absorption: 0.15,
      roughness: 0.3,
      clearcoat: 0.46,
      key_intensity: 0.68,
      key_direction: 0.28,
      rim: 0.5,
      inertia: 0.25,
      secondary_lag: 0.28,
      rebound: 0.3,
      settling: 0.28,
      motion: 0.58,
      spectral_energy_envelope: 0.72,
      center_of_mass_y: 0.04,
    },
    layerActivations: { shell: 1, energy: 0.82, face: 0.78, motion: 0.9 },
    silhouetteDelta: { width: 0.05, height: -0.02, crown: 0.06, ground: 0.06 },
    volumePolicy: { conserve: true, areaTarget: 1.029, squashStretch: 0.08 },
    centerOfMass: { x: 0, y: 0.04 },
    facialAttachment: {
      attached: true,
      latticeId: "feature-anchors-v1",
      faceScale: 0.94,
      eyeOpenness: 0.64,
      mouthOpenness: 0.28,
      residualBudget: 0.05,
    },
    materialMods: {
      pearlIntensity: 0.54,
      roughness: 0.3,
      clearcoat: 0.46,
      absorption: 0.15,
    },
    paletteMods: {
      rim: 0.5,
      keyIntensity: 0.68,
      internalGlow: 0.66,
      faceEmissive: 0.4,
    },
    embodimentId: "comet",
    expressionAffinity: "listening-orient",
  }),

  // ─── 6. Blocked ───────────────────────────────────────────────────────────
  "presence-blocked-strain": profile({
    stateId: "presence-blocked-strain",
    label: "Blocked · Strain",
    semanticIntent:
      "Effort under obstruction — compressed shell, guarded mouth, low glow.",
    personalityRead: {
      friendly: 0.3,
      intelligent: 0.7,
      slightlyUpToSomething: 0.15,
      valence: -0.35,
      arousal: 0.42,
      summary: "Blocked strain — compressed shell, guarded face, trapped energy.",
    },
    visualSignature: {
      domains: ["face", "shell", "energy", "motion"],
      primaryCue: "shell-compression-guard",
      secondaryCue: "trapped-low-glow",
      signatureChannels: SIG_CHANNELS,
    },
    channels: {
      overall_width: 0.96,
      overall_height: 0.94,
      crown_height: 0.02,
      lower_body_fullness: 0.92,
      ground_flattening: 0.12,
      face_scale: 0.96,
      eye_openness: 0.42,
      eye_spacing: -0.1,
      gaze: 0.05,
      mouth_openness: 0.18,
      mouth_width: 0.88,
      corner_pull_l: -0.12,
      corner_pull_r: -0.1,
      energy_level: 0.38,
      energy_pulse: 0.14,
      energy_lag: 0.7,
      energy_occlusion: 0.32,
      relief_amplitude: 0.35,
      relief_motion_coupling: 0.22,
      relief_energy_coupling: 0.28,
      skin_tension: 0.72,
      skin_damping: 0.62,
      skin_coupling: 0.48,
      pearl_intensity: 0.46,
      internal_glow: 0.32,
      face_emissive: 0.18,
      absorption: 0.3,
      roughness: 0.44,
      clearcoat: 0.3,
      key_intensity: 0.48,
      key_direction: -0.04,
      rim: 0.36,
      inertia: 0.6,
      secondary_lag: 0.58,
      rebound: 0.12,
      settling: 0.25,
      motion: 0.24,
      center_of_mass_y: 0.01,
    },
    layerActivations: { shell: 1, energy: 0.35, face: 0.75, motion: 0.38 },
    silhouetteDelta: { width: -0.04, height: -0.06, crown: 0.02, ground: 0.12 },
    volumePolicy: { conserve: true, areaTarget: 0.9024, squashStretch: 0.06 },
    centerOfMass: { x: 0, y: 0.01 },
    facialAttachment: {
      attached: true,
      latticeId: "feature-anchors-v1",
      faceScale: 0.96,
      eyeOpenness: 0.42,
      mouthOpenness: 0.18,
      residualBudget: 0.05,
    },
    materialMods: {
      pearlIntensity: 0.46,
      roughness: 0.44,
      clearcoat: 0.3,
      absorption: 0.3,
    },
    paletteMods: {
      rim: 0.36,
      keyIntensity: 0.48,
      internalGlow: 0.32,
      faceEmissive: 0.18,
    },
    embodimentId: "presence",
    expressionAffinity: "blocked-strain",
  }),

  // ─── 7. Pleased ───────────────────────────────────────────────────────────
  "presence-pleased-resolve": profile({
    stateId: "presence-pleased-resolve",
    label: "Pleased · Resolve",
    semanticIntent:
      "Warm contained satisfaction — soft mouth lift, even glow, no cheer caricature.",
    personalityRead: {
      friendly: 0.85,
      intelligent: 0.75,
      slightlyUpToSomething: 0.45,
      valence: 0.48,
      arousal: 0.45,
      summary: "Pleased resolve — soft mouth lift, warm glow, settled rebound.",
    },
    visualSignature: {
      domains: ["face", "shell", "energy", "motion"],
      primaryCue: "soft-mouth-lift",
      secondaryCue: "warm-even-glow",
      signatureChannels: SIG_CHANNELS,
    },
    channels: {
      overall_width: 1.01,
      overall_height: 1.03,
      crown_height: 0.07,
      lower_body_fullness: 1.02,
      ground_flattening: 0.01,
      face_scale: 1.02,
      eye_openness: 0.58,
      eye_spacing: 0.01,
      gaze: 0.06,
      mouth_openness: 0.38,
      mouth_width: 1.06,
      corner_pull_l: 0.1,
      corner_pull_r: 0.06,
      energy_level: 0.6,
      energy_pulse: 0.22,
      energy_lag: 0.32,
      energy_occlusion: 0.12,
      relief_amplitude: 0.48,
      relief_motion_coupling: 0.3,
      relief_energy_coupling: 0.42,
      skin_tension: 0.38,
      skin_damping: 0.5,
      skin_coupling: 0.46,
      pearl_intensity: 0.6,
      internal_glow: 0.56,
      face_emissive: 0.48,
      absorption: 0.16,
      roughness: 0.3,
      clearcoat: 0.48,
      key_intensity: 0.62,
      key_direction: 0.06,
      rim: 0.48,
      inertia: 0.3,
      secondary_lag: 0.34,
      rebound: 0.28,
      settling: 0.58,
      motion: 0.2,
      center_of_mass_y: 0.02,
    },
    layerActivations: { shell: 1, energy: 0.7, face: 0.9, motion: 0.4 },
    silhouetteDelta: { width: 0.01, height: 0.03, crown: 0.07, ground: 0.01 },
    volumePolicy: { conserve: true, areaTarget: 1.0403, squashStretch: 0.02 },
    centerOfMass: { x: 0, y: 0.02 },
    facialAttachment: {
      attached: true,
      latticeId: "feature-anchors-v1",
      faceScale: 1.02,
      eyeOpenness: 0.58,
      mouthOpenness: 0.38,
      residualBudget: 0.05,
    },
    materialMods: {
      pearlIntensity: 0.6,
      roughness: 0.3,
      clearcoat: 0.48,
      absorption: 0.16,
    },
    paletteMods: {
      rim: 0.48,
      keyIntensity: 0.62,
      internalGlow: 0.56,
      faceEmissive: 0.48,
    },
    embodimentId: "presence",
    expressionAffinity: "pleased-soft",
  }),

  // ─── 8. Dormant Maintain (quality floor) ──────────────────────────────────
  "dormant-orbit-maintain": profile({
    stateId: "dormant-orbit-maintain",
    label: "Dormant · Orbit Maintain",
    semanticIntent:
      "Most conservative residual orbit — identity-preserving continuity floor.",
    personalityRead: {
      friendly: 0.4,
      intelligent: 0.5,
      slightlyUpToSomething: 0.1,
      valence: 0.0,
      arousal: 0.12,
      summary:
        "Dormant residual orbit — compressed face, low glow, continuous identity.",
    },
    visualSignature: {
      domains: ["face", "shell", "energy", "motion"],
      primaryCue: "residual-orbit-compression",
      secondaryCue: "low-emissive-continuity",
      signatureChannels: SIG_CHANNELS,
    },
    channels: {
      overall_width: 0.96,
      overall_height: 0.92,
      crown_height: 0.0,
      lower_body_fullness: 0.9,
      ground_flattening: 0.08,
      // Face compressed but still lattice-attached (not floating overlay).
      face_scale: 0.9,
      eye_openness: 0.22,
      eye_spacing: 0.0,
      gaze: 0.0,
      mouth_openness: 0.12,
      mouth_width: 0.88,
      corner_pull_l: 0.0,
      corner_pull_r: 0.0,
      energy_level: 0.32,
      energy_pulse: 0.1,
      energy_lag: 0.62,
      energy_occlusion: 0.55,
      relief_amplitude: 0.28,
      relief_motion_coupling: 0.18,
      relief_energy_coupling: 0.35,
      skin_tension: 0.3,
      skin_damping: 0.58,
      skin_coupling: 0.32,
      pearl_intensity: 0.48,
      internal_glow: 0.28,
      face_emissive: 0.08,
      absorption: 0.42,
      roughness: 0.4,
      clearcoat: 0.28,
      key_intensity: 0.4,
      key_direction: 0.0,
      rim: 0.34,
      inertia: 0.55,
      secondary_lag: 0.6,
      rebound: 0.08,
      settling: 0.7,
      motion: 0.12,
      spectral_energy_envelope: 0.58,
      center_of_mass_y: 0.06,
    },
    layerActivations: { shell: 1, energy: 0.4, face: 0.35, motion: 0.25 },
    silhouetteDelta: { width: -0.04, height: -0.08, crown: 0, ground: 0.08 },
    volumePolicy: { conserve: true, areaTarget: 0.8832, squashStretch: 0.04 },
    centerOfMass: { x: 0, y: 0.06 },
    facialAttachment: {
      attached: true,
      latticeId: "feature-anchors-v1",
      faceScale: 0.9,
      eyeOpenness: 0.22,
      mouthOpenness: 0.12,
      residualBudget: 0.05,
    },
    materialMods: {
      pearlIntensity: 0.48,
      roughness: 0.4,
      clearcoat: 0.28,
      absorption: 0.42,
    },
    paletteMods: {
      rim: 0.34,
      keyIntensity: 0.4,
      internalGlow: 0.28,
      faceEmissive: 0.08,
    },
    embodimentId: "dormant-orbit",
    expressionAffinity: "neutral-settled",
  }),

  // ─── 9. Wake (transitional) ───────────────────────────────────────────────
  wake: profile({
    stateId: "wake",
    label: "Wake · Transition",
    semanticIntent:
      "Transitional rise from dormant residual orbit toward neutral availability.",
    personalityRead: {
      friendly: 0.55,
      intelligent: 0.65,
      slightlyUpToSomething: 0.35,
      valence: 0.08,
      arousal: 0.38,
      summary: "Wake transition — rising glow, reopening face, shell re-expand.",
    },
    visualSignature: {
      domains: ["face", "shell", "energy", "motion"],
      primaryCue: "rising-glow-reopen",
      secondaryCue: "shell-reexpand-from-orbit",
      signatureChannels: SIG_CHANNELS,
    },
    channels: {
      overall_width: 0.98,
      overall_height: 0.97,
      crown_height: 0.03,
      lower_body_fullness: 0.95,
      ground_flattening: 0.04,
      face_scale: 0.96,
      eye_openness: 0.42,
      eye_spacing: 0.01,
      gaze: 0.03,
      mouth_openness: 0.24,
      mouth_width: 0.94,
      corner_pull_l: 0.01,
      corner_pull_r: 0.0,
      energy_level: 0.44,
      energy_pulse: 0.2,
      energy_lag: 0.45,
      energy_occlusion: 0.28,
      relief_amplitude: 0.36,
      relief_motion_coupling: 0.3,
      relief_energy_coupling: 0.4,
      skin_tension: 0.38,
      skin_damping: 0.5,
      skin_coupling: 0.4,
      pearl_intensity: 0.52,
      internal_glow: 0.4,
      face_emissive: 0.22,
      absorption: 0.28,
      roughness: 0.36,
      clearcoat: 0.34,
      key_intensity: 0.5,
      key_direction: 0.02,
      rim: 0.38,
      inertia: 0.4,
      secondary_lag: 0.45,
      rebound: 0.18,
      settling: 0.5,
      motion: 0.3,
      spectral_energy_envelope: 0.5,
      center_of_mass_y: 0.04,
    },
    layerActivations: { shell: 1, energy: 0.55, face: 0.6, motion: 0.5 },
    silhouetteDelta: { width: -0.02, height: -0.03, crown: 0.03, ground: 0.04 },
    volumePolicy: { conserve: true, areaTarget: 0.9506, squashStretch: 0.03 },
    centerOfMass: { x: 0, y: 0.04 },
    facialAttachment: {
      attached: true,
      latticeId: "feature-anchors-v1",
      faceScale: 0.96,
      eyeOpenness: 0.42,
      mouthOpenness: 0.24,
      residualBudget: 0.05,
    },
    materialMods: {
      pearlIntensity: 0.52,
      roughness: 0.36,
      clearcoat: 0.34,
      absorption: 0.28,
    },
    paletteMods: {
      rim: 0.38,
      keyIntensity: 0.5,
      internalGlow: 0.4,
      faceEmissive: 0.22,
    },
    embodimentId: "presence",
    expressionAffinity: "neutral-social",
    transitional: true,
  }),
}) as Record<EightStateVisualId, CharacterStateProfile>;

export const EIGHT_STATE_VISUAL_ORDER: readonly EightStateVisualId[] =
  Object.freeze([
    "presence-neutral-settled",
    "presence-listening-receive",
    "presence-thinking-knit",
    "presence-recognition-spark",
    "comet-executing-drive",
    "presence-blocked-strain",
    "presence-pleased-resolve",
    "dormant-orbit-maintain",
    "wake",
  ]);

export const EIGHT_STATE_HOLD_ORDER: readonly EightStateVisualId[] =
  Object.freeze([
    "presence-neutral-settled",
    "presence-listening-receive",
    "presence-thinking-knit",
    "presence-recognition-spark",
    "comet-executing-drive",
    "presence-blocked-strain",
    "presence-pleased-resolve",
    "dormant-orbit-maintain",
  ]);

export function getCharacterStateProfile(
  stateId: string,
): CharacterStateProfile | null {
  if (stateId in GASPER_STATE_PROFILES) {
    return GASPER_STATE_PROFILES[stateId as EightStateVisualId];
  }
  return null;
}

export function listCharacterStateProfiles(): CharacterStateProfile[] {
  return EIGHT_STATE_VISUAL_ORDER.map((id) => GASPER_STATE_PROFILES[id]);
}

export function listHoldStateProfiles(): CharacterStateProfile[] {
  return EIGHT_STATE_HOLD_ORDER.map((id) => GASPER_STATE_PROFILES[id]);
}

export function isEightStateVisualId(id: string): id is EightStateVisualId {
  return id in GASPER_STATE_PROFILES;
}

export function getDormantQualityFloor(): CharacterStateProfile {
  return GASPER_STATE_PROFILES["dormant-orbit-maintain"];
}

export function getNeutralProfile(): CharacterStateProfile {
  return GASPER_STATE_PROFILES["presence-neutral-settled"];
}

/** Clone channels for a state (immutable snapshot). */
export function channelsForState(stateId: string): CharacterChannelMap | null {
  const p = getCharacterStateProfile(stateId);
  return p ? { ...p.channels } : null;
}
