/**
 * Per-state blink and gaze/saccade policies (MegaBook §10).
 */

import type { EightStateId, GazeBlinkPolicy } from "./types";

export const GAZE_BLINK_POLICIES: Record<EightStateId, GazeBlinkPolicy> = {
  "presence-neutral-settled": {
    stateId: "presence-neutral-settled",
    blinkMinGapSec: 8.0,
    blinkMaxGapSec: 14.0,
    blinkCloseDur: [0.12, 0.18],
    blinkOpenDur: [0.18, 0.28],
    saccadeMinGapSec: 1.4,
    saccadeMaxGapSec: 4.0,
    saccadeAmp: 0.1,
    gazeCenterBias: 0,
    allowBlink: true,
    allowSaccade: true,
  },
  "presence-listening-receive": {
    stateId: "presence-listening-receive",
    blinkMinGapSec: 8.2,
    blinkMaxGapSec: 14.0,
    blinkCloseDur: [0.12, 0.16],
    blinkOpenDur: [0.18, 0.26],
    saccadeMinGapSec: 2.2,
    saccadeMaxGapSec: 5.0,
    saccadeAmp: 0.05,
    gazeCenterBias: 0.14,
    allowBlink: true,
    allowSaccade: true,
  },
  "presence-thinking-knit": {
    stateId: "presence-thinking-knit",
    blinkMinGapSec: 8.0,
    blinkMaxGapSec: 13.0,
    blinkCloseDur: [0.14, 0.20],
    blinkOpenDur: [0.20, 0.30],
    saccadeMinGapSec: 1.6,
    saccadeMaxGapSec: 3.8,
    saccadeAmp: 0.12,
    gazeCenterBias: -0.08,
    allowBlink: true,
    allowSaccade: true,
  },
  "presence-recognition-spark": {
    stateId: "presence-recognition-spark",
    blinkMinGapSec: 8.5,
    blinkMaxGapSec: 13.0,
    blinkCloseDur: [0.12, 0.16],
    blinkOpenDur: [0.18, 0.24],
    saccadeMinGapSec: 0.6,
    saccadeMaxGapSec: 1.4,
    saccadeAmp: 0.14,
    gazeCenterBias: 0.18,
    allowBlink: true,
    allowSaccade: true,
  },
  "comet-executing-drive": {
    stateId: "comet-executing-drive",
    blinkMinGapSec: 8.0,
    blinkMaxGapSec: 13.0,
    blinkCloseDur: [0.12, 0.16],
    blinkOpenDur: [0.18, 0.26],
    saccadeMinGapSec: 2.0,
    saccadeMaxGapSec: 4.5,
    saccadeAmp: 0.06,
    gazeCenterBias: 0.12,
    allowBlink: true,
    allowSaccade: true,
  },
  "presence-blocked-strain": {
    stateId: "presence-blocked-strain",
    blinkMinGapSec: 8.0,
    blinkMaxGapSec: 13.0,
    blinkCloseDur: [0.16, 0.24],
    blinkOpenDur: [0.20, 0.32],
    saccadeMinGapSec: 2.5,
    saccadeMaxGapSec: 5.5,
    saccadeAmp: 0.04,
    gazeCenterBias: 0.05,
    allowBlink: true,
    allowSaccade: true,
  },
  "presence-pleased-resolve": {
    stateId: "presence-pleased-resolve",
    blinkMinGapSec: 8.0,
    blinkMaxGapSec: 13.0,
    blinkCloseDur: [0.12, 0.18],
    blinkOpenDur: [0.20, 0.30],
    saccadeMinGapSec: 1.3,
    saccadeMaxGapSec: 3.2,
    saccadeAmp: 0.09,
    gazeCenterBias: 0,
    allowBlink: true,
    allowSaccade: true,
  },
  "dormant-orbit-maintain": {
    stateId: "dormant-orbit-maintain",
    blinkMinGapSec: 99,
    blinkMaxGapSec: 99,
    blinkCloseDur: [0.12, 0.12],
    blinkOpenDur: [0.18, 0.18],
    saccadeMinGapSec: 99,
    saccadeMaxGapSec: 99,
    saccadeAmp: 0,
    gazeCenterBias: 0,
    allowBlink: false,
    allowSaccade: false,
  },
  wake: {
    stateId: "wake",
    blinkMinGapSec: 8.0,
    blinkMaxGapSec: 13.0,
    blinkCloseDur: [0.12, 0.18],
    blinkOpenDur: [0.18, 0.26],
    saccadeMinGapSec: 1.2,
    saccadeMaxGapSec: 2.8,
    saccadeAmp: 0.08,
    gazeCenterBias: 0.04,
    allowBlink: true,
    allowSaccade: true,
  },
};

export function policyFor(stateId: EightStateId): GazeBlinkPolicy {
  return GAZE_BLINK_POLICIES[stateId];
}
